INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'Con Bạn Lấy Chồng - Ờ Phương x Vinh Z x Blackbi | OST CON NHÓT MÓT CHỒNG – ĐANG CHIẾU TẠI RẠP', N'BfARUE6Tx1U', N'https://img.youtube.com/vi/BfARUE6Tx1U/maxresdefault.jpg', 3, 3, N' Vũ Ngọc Đãng', N'Thu Trang, Thái Hòa, Tiến Luật', N' Phim  Tình cảm', N'Tình cảm gia đình', N'Nhót, người phụ nữ “chưa kịp già” đã sắp bị mãn kinh, vội vàng đi tìm chồng. Nhưng sâu thẳm trong cô là khao khát có một đứa con và luôn muốn hàn gắn với người cha suốt ngày say xỉn của mình.', 20000, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'[S6] Doraemon Tập 298 - Hồn Ma Xuất Hiện - Tiếng Việt', N'R5aLRIu3Sxs', N'https://img.youtube.com/vi/R5aLRIu3Sxs/maxresdefault.jpg', 5, 4, N'Nguyễn Ngọc Ngân', N'#doraemontiengviet #nobita #doraemon', N'Phim hoạt hình', N'🎉🎉Đăng ký POPS Kids Learn để tham gia các khóa học online tương tác với giảng viên ngay nhé 👉 https://popskids.onelink.me/X36W/POPS...', N'Doraemon được mua bản quyền và được cập nhật phát sóng trên ứng dụng giải trí POPS Kids & kênh YouTube POPS Kids. Đây là bộ phim chuyển thể từ truyện tranh hấp dẫn nhất Nhật Bản: Doraemon của tác giả Fujiko Fujio sáng tác từ năm 1969. Bộ truyện kể về một chú mèo máy tên Doraemon đến từ thế kỉ 22 để giúp một cậu bé lớp 5 hậu đậu tên là Nobi Nobita. Sewashi (Nobito), cháu ba đời của Nobita gửi Doraemon về quá khứ nhằm giúp đỡ ông mình, qua đó cải thiện được hoàn cảnh của con cháu Nobita sau này. Các tập phim Doraemon thường xoay quanh những rắc rối hay xảy ra với cậu bé Nobita. Cốt truyện thường gặp nhất là Nobita trở về nhà khóc lóc với Doraemon vì những rắc rối mà cậu gặp phải ở trường học hoặc với bạn bè. Sau khi bị cậu van nài hoặc thúc giục, Doraemon sẽ lấy ra một bảo bối trong chiếc túi thần kỳ trước bụng để giúp Nobita giải quyết rắc rối của mình. Nhưng Nobita sẽ lại thường đi quá xa so với dự định ban đầu của Doraemon. Cậu thường lấy sự ưu việt của bảo bối để trêu ghẹo mọi người nên cuối cùng bị phản tác dụng, bị bảo bối gây phiền phức. Có đôi khi những người bạn của Nobita, thường là Suneo hoặc Jaian lại lấy trộm những bảo bối và sử dụng chúng không đúng mục đích. Kết thúc mỗi câu chuyện, những ai sử dụng sai mục đích bảo bối sẽ phải chịu hậu quả do mình gây ra, từ đó khán giả sẽ rút ra được bài học cho riêng mình.', 21000, 0, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'[S6] Doraemon Tập 299 - Kế Hoạch Ngày Sinh Nhật, Máy Cải Lão Hoàn Đồng - Tiếng Việt', N'0HOa-A0rt_Q', N'https://img.youtube.com/vi/0HOa-A0rt_Q/maxresdefault.jpg', 1, 2, N'Nguyễn Ngọc Ngạn', N'#doraemontiengviet #nobita #doraemon', N'Phim hoạt hình', N'🎉🎉Đăng ký POPS Kids Learn để tham gia các khóa học online tương tác với giảng viên ngay nhé 👉 https://popskids.onelink.me/X36W/POPS...', N'Doraemon được mua bản quyền và được cập nhật phát sóng trên ứng dụng giải trí POPS Kids & kênh YouTube POPS Kids. Đây là bộ phim chuyển thể từ truyện tranh hấp dẫn nhất Nhật Bản: Doraemon của tác giả Fujiko Fujio sáng tác từ năm 1969. Bộ truyện kể về một chú mèo máy tên Doraemon đến từ thế kỉ 22 để giúp một cậu bé lớp 5 hậu đậu tên là Nobi Nobita. Sewashi (Nobito), cháu ba đời của Nobita gửi Doraemon về quá khứ nhằm giúp đỡ ông mình, qua đó cải thiện được hoàn cảnh của con cháu Nobita sau này. Các tập phim Doraemon thường xoay quanh những rắc rối hay xảy ra với cậu bé Nobita. Cốt truyện thường gặp nhất là Nobita trở về nhà khóc lóc với Doraemon vì những rắc rối mà cậu gặp phải ở trường học hoặc với bạn bè. Sau khi bị cậu van nài hoặc thúc giục, Doraemon sẽ lấy ra một bảo bối trong chiếc túi thần kỳ trước bụng để giúp Nobita giải quyết rắc rối của mình. Nhưng Nobita sẽ lại thường đi quá xa so với dự định ban đầu của Doraemon. Cậu thường lấy sự ưu việt của bảo bối để trêu ghẹo mọi người nên cuối cùng bị phản tác dụng, bị bảo bối gây phiền phức. Có đôi khi những người bạn của Nobita, thường là Suneo hoặc Jaian lại lấy trộm những bảo bối và sử dụng chúng không đúng mục đích. Kết thúc mỗi câu chuyện, những ai sử dụng sai mục đích bảo bối sẽ phải chịu hậu quả do mình gây ra, từ đó khán giả sẽ rút ra được bài học cho riêng mình.', 10000, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 216 - Ba Chàng Trai Hạnh Phúc', N'4FLO4ic6GNg', N'https://img.youtube.com/vi/4FLO4ic6GNg/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N' Thái Vũ, Huỳnh Phương,Vinh Râu, Ribi, Thúy Kiều, Phương Nam,Thông Nguyễn, Kim Suri ,Quốc Trường, Mr Park Sungho, Minh Lộc, Đức Duy, Khánh Huy, Hải ngân cùng với một số diễn viên khác....', N'Phim hài', N'Phim Hài', N'Khởi nghiệp đơn giản với Gà chiên Chicken Plus: https://www.facebook.com/CHICKENPLUS.VN/ Lao động là vinh quang, lang thang là chết đói kkkk', 15000, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'Mùa Hè Rực Rỡ : Tập 4 - Vạch Mặt || FAPtv Phim Tuổi Teen', N'n5MJDZkX3Rs', N'https://img.youtube.com/vi/n5MJDZkX3Rs/maxresdefault.jpg', 2, 2, N'Trần Đức Viễn', N'Doramon', N'Phim hài', N'#FAPTV #phimhay #phimtinhcam #Muaherucro #phimhai #leadwithlove  #lofmalto ', N'Mùa Hè Rực Rỡ : Tập 4 - Vạch Mặt || FAPtv Phim Tuổi Teen Phim được phát sóng vào 19h tối thứ 7 mỗi tuần, mời các bạn đón xem! Sữa Lúa Mạch Sôcôla Lof Malto - Lead with Lof - Năng lượng cho GenZ, mua đi chờ chi mấy homies. Mua hàng tại: https://bit.ly/mualofmaltongay', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'Mùa Hè Rực Rỡ : Tập 3 - Người Lạ Mà Quen || FAPtv Phim Tuổi Teen', N'WWreBGNp6cg', N'https://img.youtube.com/vi/WWreBGNp6cg/maxresdefault.jpg', 2, 3, N'Trần Đức Viễn, Vinh Râu', N'Đức Viễn, Vinh Râu,Thái Vũ, Huỳnh Phương, Nikola , Thúy Kiều, Diễm Châu, Yến Vy, Kim Thảo, Phúc Vũ, Quốc Hưng, Mai Thy, Minh Thảo,Bảo Quyên', N'Phim Hài', N'Phim Hài', N'Mùa Hè Rực Rỡ : Tập 3 - Người Lạ Mà Quen || FAPtv Phim Tuổi Teen Phim được phát sóng vào 19h tối thứ 7 mỗi tuần, mời các bạn đón xem! Sữa Lúa Mạch Sôcôla Lof Malto - Lead with Lof - Năng lượng cho GenZ, mua đi chờ chi mấy homies. Mua hàng tại: https://bit.ly/mualofmaltongay', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'Mùa Hè Rực Rỡ : Tập 2 - Bí Mật Ngôi Nhà Hoang || FAPtv Phim Tuổi Teen', N'KFzlcUtLu24', N'https://img.youtube.com/vi/KFzlcUtLu24/maxresdefault.jpg', 2, 3, N'Trần Đức Viễn, Vinh Râu', N'Đức Viễn, Vinh Râu,Thái Vũ, Huỳnh Phương, Nikola , Thúy Kiều, Diễm Châu, Yến Vy, Kim Thảo, Phúc Vũ, Quốc Hưng, Mai Thy, Minh Thảo,Bảo Quyên', N'Phim Hài', N'Phim Hài', N'Mùa Hè Rực Rỡ : Tập 2 - Bí Mật Ngôi Nhà Hoang || FAPtv Phim Tuổi Teen Phim được phát sóng vào 19h tối thứ 7 mỗi tuần, mời các bạn đón xem! Sữa Lúa Mạch Sôcôla Lof Malto - Lead with Lof - Năng lượng cho GenZ, mua đi chờ chi mấy homies.', 25000, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'Mùa Hè Rực Rỡ : Tập 1 - Về Miền Tây || FAPtv Phim Tuổi Teen', N'UE5VYYkbW0Q', N'https://img.youtube.com/vi/UE5VYYkbW0Q/maxresdefault.jpg', 2, 3, N'Trần Đức Viễn, Vinh Râu', N'Đức Viễn, Vinh Râu,Thái Vũ, Huỳnh Phương, Nikola , Thúy Kiều, Diễm Châu, Yến Vy, Kim Thảo, Phúc Vũ, Quốc Hưng, Mai Thy, Minh Thảo,Bảo Quyên', N'Phim Hài', N'Phim Hài', N'Mùa Hè Rực Rỡ : Tập 1 - Về Miền Tây || FAPtv Phim Tuổi Teen Phim được phát sóng vào 19h tối thứ 7 mỗi tuần, mời các bạn đón xem! Sữa Lúa Mạch Sôcôla Lof Malto - Lead with Lof - Năng lượng cho GenZ, mua đi chờ chi mấy homies. Mua hàng tại: https://bit.ly/mualofmaltongay', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 290: Cú Ngã Đầu Đời', N'GalCJ-ZAd0k', N'https://img.youtube.com/vi/GalCJ-ZAd0k/maxresdefault.jpg', 2, 3, N'Trần Đức Viễn', N'Ribi Sachi, Vinh Râu, Thái Vũ, Trang Nơ, Uy Trần', N'Phim Hài', N'#FAPTV #cơmnguội  #chongnanghiruscar #suachongnanghiruscar #hiruscarpostacne', N'Trải nghiệm trọn bộ Routine Hiruscar tại : Shopee: https://bit.ly/HIRUSCARxFAPTV hoặc mua ngay tại các cửa hàng, nhà thuốc Long Châu, An Khang, Pharmacity, Guardian, Watson và Medicare ', 17000, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội Tập 289 : Cô Shipper Và Hoàng Tử', N'zimJ6o8wzAo', N'https://img.youtube.com/vi/zimJ6o8wzAo/maxresdefault.jpg', 4, 1, N'Trần Đức Viễn', N'Ribi Sachi, Vinh Râu, Thái Vũ, Trang Nơ, Uy Trần', N'Phim Hài', N'#FAPTV #cơmnguội  #chongnanghiruscar #suachongnanghiruscar #serumhiruscar', N'Trải nghiệm trọn bộ Routine Hiruscar tại : Shopee: https://bit.ly/HIRUSCARxFAPTV hoặc mua ngay tại các nhà thuốc, các cửa hàng Guardian, Watson và Medicare', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội 288: Đi Học Cùng Con', N'8ThM36Os_OA', N'https://img.youtube.com/vi/8ThM36Os_OA/maxresdefault.jpg', 1, 5, N'Trần Đức Viễn', N' Ribi Sachi, Vinh Râu, Thái Vũ, Trang Nơ, Uy Trần, Mai Xuân Thứ, Tuyết Nguyễn, Kim SuriLớp học diễn viên : Minh Thành, Nguyễn Hường, Susu Võ, Phú Quí, Hà Vy  ', N'Phim Hài', N'#FAPTV #cơmnguội #Hiruscar #HiruscarSpotGel ', N'Trải nghiệm trọn bộ Routine Hiruscar tại : Shopee: https://shopee.vn/hiruscar_vietnam hoặc mua ngay tại các nhà thuốc, các cửa hàng Guardian, Watson và Medicare', 19999, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội 287 : Hai Chàng Một Tình Yêu', N'rdwl9WrSYY0', N'https://img.youtube.com/vi/rdwl9WrSYY0/maxresdefault.jpg', 5, 1, N'Trần Đức Viễn', N'Vinh Râu, Thái Vũ, Huỳnh Phương, Ribi Sachi, Thuý Kiều, Trang Nơ, Uy Trần', N'Phim Hài', N'#FAPTV #comnguoi #Cơmnguội #thaivu #vinhrau #huynhphuong #ribisachi #phimhai2023', N'Chúc cả nhà có một kỳ nghỉ lễ thật vui vẻ bên gia đình và người thân. Cùng nhau quây quần xem Cơm Nguội với những tiếng cười vui vẻ nhennnn <3', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội 280: Về Nhà Với Mẹ - Phim HÀI TẾT 2023', N'xe2AY0LnVms', N'https://img.youtube.com/vi/xe2AY0LnVms/maxresdefault.jpg', 22, 1, N'Trần Đức Viễn', N'Ribi Sachi, Vinh Râu, Thái Vũ, Huỳnh Phương, Thuý Kiều, Trang Nơ, Uy Trần', N'Phim Hài', N'#FAPTV #comnguoi #Cơmnguội #thaivu #vinhrau #huynhphuong #ribisachi #phimhai2023', N'Chúc các bạn iu xem phim vui vẻ, nhớ cho chúng mình xin ý kiến nhen!!', 51000, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 140 - Ba Anh Yêu Mẹ Em', N'tqfzul636Ko', N'https://img.youtube.com/vi/tqfzul636Ko/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Vinh Râu, Thái Vũ, Ribi Sachi, Thúy Kiều, Kim Suri,  Fap Team.', N'Phim hài', N'Xin cảm ơn Trung Tâm Hướng Nghiệp Á Âu đã tài trợ địa điểm quay làm bánh cho ekip', N'FAPtv Cơm Nguội: Tập 140 - Ba Anh Yêu Mẹ Em Bánh kem sữa tươi Rosio với bốn hương vị: Trà xanh Nhật Bản, Hạt chia Peru, Phô mai Úc và Red Velvet Hoa Kỳ. Cốt bánh mềm mịn quyện cùng lớp kem được làm từ 100% sữa tươi mang đến vị ngon khó cưỡng ❤ Fanpage: https://www.facebook.com/BanhRosio/ ❤ Website: https://goo.gl/X7TibQ', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 215 - Mỗi Khi Em Cười', N'D9w-5LqvJbg', N'https://img.youtube.com/vi/D9w-5LqvJbg/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Vinh Râu, Thái Vũ, Ribi Sachi, Thúy Kiều, Kim Suri,  Fap Team.', N'Phim hài', N'Xin cảm ơn Trung Tâm Hướng Nghiệp Á Âu đã tài trợ địa điểm quay làm bánh cho ekip', N'qwwdqwqdwdwdq', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội : Tập 248 - Chuyện Kiều', N'2ajGlMbyc0Q', N'https://img.youtube.com/vi/2ajGlMbyc0Q/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Thái Vũ, Vinh Râu, Huỳnh Phương, Uy Trần, Ribi Sachi, Thúy Kiều, Trang Nơ, cùng với một số diễn viên khác....', N'Phim hài', N'#FAPTV #Cơmnguội #Hiruscar #ChuyenKieu #TruyenKieu', N'FAPtv Cơm Nguội : Tập 248 - Chuyện Kiều Hiruscar Silicone Pro đang có chương trình khuyến mãi hấp dẫn tại Lazada: https://bit.ly/lazada-hiruscar từ 20 đến 31/03. Các bạn mua ngay kẻo lỡ nhé! */// Nếu trong khi xem phim có xuất hiện quảng cáo, hãy xem hoặc click quảng cáo để ủng hộ chúng tôi ///**', 45000, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 203 - Duyên Phận', N'qhUhGKVampw', N'https://img.youtube.com/vi/qhUhGKVampw/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Vinh Râu, Thái Vũ, Huỳnh Phương, Ribi, Hào Wong, Hải Lê... Cùng với các bạn diễn viên khác.', N'Phim hài', N'*/// Nếu trong khi xem phim có xuất hiện quảng cáo, hãy xem hoặc click quảng cáo để ủng hộ chúng tôi ///**', N'FAPtv Cơm Nguội: Tập 203 - Duyên Phận  #FAPTV #Cơmnguội #Duyenphan #DuyênPhận', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 176 - Quán Cafe Bất Ổn: Tình Đồng Chí', N'JhO59Hjc-CQ', N'https://img.youtube.com/vi/JhO59Hjc-CQ/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Vinh Râu, Thái Vũ, Huỳnh Phương, Ribi,Thúy Kiều,Hoàng Siêm, Hào Wong,... Cùng với các bạn diễn viên khác.', N'Phim hài', N'*/// Nếu trong khi xem phim có xuất hiện quảng cáo, hãy xem hoặc click quảng cáo để ủng hộ chúng tôi ///**', N'FAPtv Cơm Nguội: Tập 176 -  Sự trở lại của Quán Cafe Bất Ổn: Tình Đồng Chí Chỉ trong ngày 11.08, chơi Free Fire - Trúng Iphone X và nhiều quà kỷ niệm 1 năm tuổi nha. Tải game ngay: https://goo.gl/aUpz49 để chơi cùng FAPTV nhé!!!', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 239 : Bạn Gái Tôi Là Ngôi Sao', N'kK-TOQuegas', N'https://img.youtube.com/vi/kK-TOQuegas/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Thái Vũ, Vinh Râu, Huỳnh Phương, Uy Trần, Ribi Sachi, Kim Ngân, Thúy Kiều, Mai Xuân Thứ, Tuyết Nguyễn, Huỳnh Sơn....  cùng với một số diễn viên khác....', N'Phim hài', N'#FAPTV #Cơmnguội #KoreanStrawberry */// Nếu trong khi xem phim có xuất hiện quảng cáo, hãy xem hoặc click quảng cáo để ủng hộ chúng tôi ///**', N'FAPtv Cơm Nguội: Tập 239 : Bạn Gái Tôi Là Ngôi Sao Dâu Tây Hàn Quốc hiện đăng có bán tại các siêu thị và cửa hàng tiện lợi, nhanh tay sở hữu ngay 1 hộp và làm quà tặng cho mùa Giáng Sinh này nhé! Trong clip chúng tôi sử dụng bài hát trong tập cơm nguội Bạn Gái Tôi Là Ngôi Sao Call Me Out - Loving Caliber', 72000, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 239 : Bạn Gái Tôi Là Ngôi Sao', N'ATd0zK5yRxQ', N'https://img.youtube.com/vi/ATd0zK5yRxQ/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Thái Vũ, Vinh Râu, Huỳnh Phương, Uy Trần, Ribi Sachi, Kim Ngân, Thúy Kiều, Mai Xuân Thứ, Tuyết Nguyễn, Huỳnh Sơn....  cùng với một số diễn viên khác....', N'Phim hài', N'*/// Nếu trong khi xem phim có xuất hiện quảng cáo, hãy xem hoặc click quảng cáo để ủng hộ chúng tôi ///**', N'FAPtv Cơm Nguội: Tập 239 : Bạn Gái Tôi Là Ngôi Sao Dâu Tây Hàn Quốc hiện đăng có bán tại các siêu thị và cửa hàng tiện lợi, nhanh tay sở hữu ngay 1 hộp và làm quà tặng cho mùa Giáng Sinh này nhé! Trong clip chúng tôi sử dụng bài hát trong tập cơm nguội Bạn Gái Tôi Là Ngôi Sao Call Me Out - Loving Caliber', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 111 - Theo Đuổi Đam Mê', N'OivYGG7BVNI', N'https://img.youtube.com/vi/OivYGG7BVNI/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Thái Vũ, Vinh Râu, Huỳnh Phương, Uy Trần, Ribi Sachi, Kim Ngân, Thúy Kiều, Mai Xuân Thứ, Tuyết Nguyễn, Huỳnh Sơn....  cùng với một số diễn viên khác....', N'Phim hài', N'*/// Nếu trong khi xem phim có xuất hiện quảng cáo, hãy xem hoặc click quảng cáo để ủng hộ chúng tôi ///**', N'FAPtv Cơm Nguội: Tập 239 : Bạn Gái Tôi Là Ngôi Sao Dâu Tây Hàn Quốc hiện đăng có bán tại các siêu thị và cửa hàng tiện lợi, nhanh tay sở hữu ngay 1 hộp và làm quà tặng cho mùa Giáng Sinh này nhé! Trong clip chúng tôi sử dụng bài hát trong tập cơm nguội Bạn Gái Tôi Là Ngôi Sao Call Me Out - Loving Caliber', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'Mùa Hè Rực Rỡ : Tập 6 - Lời Xin Lỗi || FAPtv Phim Tuổi Teen', N'-YspL3peIRw', N'https://img.youtube.com/vi/-YspL3peIRw/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Đức Viễn, Vinh Râu,Thái Vũ, Huỳnh Phương, Nikola , Thúy Kiều, Diễm Châu, Yến Vy, Kim Thảo, Phúc Vũ, Quốc Hưng, Mai Thy, Minh Thảo, Bảo Quyên', N'Phim hài', N'Link TVC Lof Malto:      • SỮA CHUA UỐNG LOF...  ', N'Mùa Hè Rực Rỡ : Tập 6 - Lời Xin Lỗi || FAPtv Phim Tuổi Teen Phim được phát sóng vào 19h tối thứ 7 mỗi tuần, mời các bạn đón xem! Sữa Lúa Mạch Sôcôla Lof Malto - Lead with Lof - Năng lượng cho GenZ, mua đi chờ chi mấy homies. Mua hàng tại: https://bit.ly/mualofmaltongay', 51000, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 111 - Theo Đuổi Đam Mê', N'MqoEVy_IcuM', N'https://img.youtube.com/vi/MqoEVy_IcuM/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Vinh Râu, Thái Vũ, Ribi Sachi, Thúy Kiều, Kim Suri,  Fap Team.', N'Phim hài', N'Xin cảm ơn Trung Tâm Hướng Nghiệp Á Âu đã tài trợ địa điểm quay làm bánh cho ekip', N'Dynasty Warriors: Unleashed – Huyền thoại vẫn mãi là huyền thoại-Tải game tại: https://i.nx.com/34B-Trang chủ:http://unleashed.nexon.com/vn-Fanpage: https://www.facebook.com/dwUNLEASHED/ ', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES ( N'FAPtv Cơm Nguội: Tập 118 - Thi Rớt', N'4MfSPmHQMxk', N'https://img.youtube.com/vi/4MfSPmHQMxk/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Vinh Râu, Thái Vũ, Huỳnh Phương, Ribi Sachi, Kim Suri,Quốc Trường,Gia lâm, Fap Team.', N'Phim hài', N'Vì sao Huỳnh Phương học giỏi mà thi rớt, còn Vinh và Thái học dốt lại thi.... rớt luôn???', N'"Học cao đẳng tại FPT Polytechnic Đào tạo cực chuẩn không thiếu gì 2 năm 4 tháng làm được việc Doanh nghiệp chào đón, chẳng sợ chi."', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES ( N'Tuy Hai Mà Một - Tập Full | FAPTV', N'6dJBEHP8ESg', N'https://img.youtube.com/vi/6dJBEHP8ESg/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Thái Vũ, Huỳnh Phương, Vinh Râu, Uy Trần, Ribi Sachi, Mai Xuân Thứ, Kim Ngân, cùng với một số diễn viên khác....', N'Phim hài', N'*/// Nếu trong khi xem phim có xuất hiện quảng cáo, hãy xem hoặc click quảng cáo để ủng hộ chúng tôi ///**', N'Tải Free Fire ngay để nhập vai, bắn súng và chinh phục Top 1: https://freefire.onelink.me/Io8U/38a3 #FAPTV #Cơmnguội #FreeFire ', 11000, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES ( N'BỐ GIÀ [FULL] - PHIM GIA ĐÌNH | TRẤN THÀNH, MÁ GIÀU, LÊ GIANG, ANH ĐỨC, TUẤN TRẦN, UYỂN ÂN', N'oA-BhGNK7qw', N'https://img.youtube.com/vi/oA-BhGNK7qw/maxresdefault.jpg', 0, 0, N'TRẤN THÀNH', N'TRẤN THÀNH, MÁ GIÀU, LÊ GIANG, ANH ĐỨC, TUẤN TRẦN, UYỂN ÂNN, LÊ QUỐC NAM, LÂM VỸ DẠ, QUỐC KHÁNH, TRÚC NHÂN, ALI HOÀNG DƯƠNG, TRANG HÝ, BÀ TÂN VLOG.', N'Tình cảm', N'#bogia #tranthanh #hariwon #ngocgiau #legiang #trucnhan #huynhuyenan #lamvyda #anhduc #tuantran #tranghy  #phimchieurap #phimgiadinh', N'BỐ GIÀ là một bộ phim Web drama tình cảm gia đình, một dự án phim hài Tết 2020 của Trấn Thành. Trong phim, Trấn Thành đóng vai chính - một ông bố tính cục súc, bảo thủ nhưng rất thương con, luôn quan tâm gia đình. Phim xoay quanh đề tài thế giới giang hồ, xoáy vào chuyện giữ bản chất lương thiện hay chạy theo tiền bạc. Êkíp quay trong 11 ngày. Đạo diễn là Mr. Tô - người thực hiện các web-drama Thập tam muội, Thập tứ cô nương, Vi Cá tiền truyện... Ngoài Lê Giang, Tuấn Trần, em gái Trấn Thành cũng tham gia một vai. ------- Chào mừng bạn đến với Youtube chính thức được trực tiếp quản lý bởi MC Trấn Thành, những thành viên của gia đình TRAN THANH Official và METUB Network. Các bạn nhớ Subscribe, Like và Share để ủng hộ tinh thần cho Trấn Thành và nhận được những thông tin, video mới nhất về các hoạt động nghệ thuật của MC Trấn Thành  nhé.Fanpage chính thức: https://www.facebook.com/tran.thanh.ne Kênh youtube chính thức: http://metub.net/tranthanh Rất cảm ơn các anh chị, các bạn đã ủng hộ chúng tôi trong suốt thời gian qua!', 25000, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'Siêu Sao Siêu Ngố Full HD - Trường Giang | Hài Tết Việt Nam Mới Nhất 2023', N'o00gSlZcwnQ', N'https://img.youtube.com/vi/o00gSlZcwnQ/maxresdefault.jpg', 0, 0, N'Trường Giang', N'Trường Giang, Sam, và cùng các diễn viên khác', N'Phim hài tết', N' #truonggiang #haitet ', N'Siêu Sao Siêu Ngố Full HD - Trường Giang | Hài Tết Việt Nam Mới Nhất 2023 #truonggiang #haitet Duyên Kiếp Full Bộ : https://bit.ly/3cSDwAn Đấu Trí Full :• Danh sách phát', 0, 1, CAST(N'2023-08-01T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv || Lớp Chuyên ', N'1P62c7UYcx8', N'https://img.youtube.com/vi/1P62c7UYcx8/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Vinh Râu, Thái Vũ, Ribi Sachi, Thúy Kiều, Kim Suri,  Fap Team.', N'Phim hài', N'#cơmnguội  #thaivu  #vinhrau  #huynhphuong  #ribisachi  #phimhocduong2022  #lopchuyen #cabiet', N'FAPtv || Lớp Chuyên "Cá Biệt": Tập 11 (Tập Cuối) Thể loại phim: học đường, tình cảm, hài hước #FAPTV #Cơmnguội  #leadwithLOF #cơmnguội  #thaivu  #vinhrau  #huynhphuong  #ribisachi  #phimhocduong2022  #lopchuyen #cabiet ------------- Sữa Lúa Mạch Sôcôla Lof Malto - Lead with Lof - Năng lượng cho GenZ, mua đi chờ chi mấy homies. Mua hàng tại: https://bit.ly/mualofmaltongay', 0, 1, CAST(N'2023-08-02T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 164 - Trại Hè Cuồng Nhiệt Phần 2', N'z3v4zgUp8ao', N'https://img.youtube.com/vi/z3v4zgUp8ao/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn, Vinh Râu', N'Vinh Râu, Thái Vũ, Ribi Sachi, Thúy Kiều, Kim Suri,  Fap Team.', N'Phim hài', N'*/// Nếu trong khi xem phim có xuất hiện quảng cáo, hãy xem hoặc click quảng cáo để ủng hộ chúng tôi ///**', N'FAPtv Cơm Nguội - TRẠI HÈ CUỒNG NHIỆT phần 2 tiết lộ nhiều mẫu thuẫn của nhóm, và đỉnh điểm là sự chia rẽ khiến cho chuyến đi có thể bị dừng lại. Chuyện gì đã xảy ra nhỉ? Xem phim hay nhận quà liền tay từ Sunplay: http://bit.ly/SPYTFTV1 Đón xem Phần 3 vào ngày: 25/05/2018', 13000, 1, CAST(N'2023-08-02T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'TĂNG PHÚC |"SÀI GÒN YẾU ĐUỐI BIẾT DỰA VÀO AI?"(Huỳnh Quốc Huy) | Live in THE ROOFTOP SHOW 25.07.2020', N'gCMUPGC7rQc', N'https://img.youtube.com/vi/gCMUPGC7rQc/maxresdefault.jpg', 0, 0, N'NHẬT NGUYỄN', N'FAPtv Cơm Nguội: Tập 176 - Quán Cafe Bất Ổn: Tình Đồng Chí', N'Nhạc', N'Xin cảm ơn Trung Tâm Hướng Nghiệp Á Âu đã tài trợ địa điểm quay làm bánh cho ekip', N'▶ More information about Tăng Phúc:   ♫ Youtube: http://popsww.com/tangphuc ♫ Instagram: https://www.instagram.com/tang._.phuc/ ♫ Facebook: https://www.facebook.com/tangphucoffi... ♫ Fanpage: https://www.facebook.com/tangphucoffi...', 25000, 0, CAST(N'2023-08-04T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 204 - Người Cha Đãng Trí', N'RPnIq_59dJc', N'https://img.youtube.com/vi/RPnIq_59dJc/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'FAPtv Cơm Nguội: Tập 176 - Quán Cafe Bất Ổn: Tình Đồng Chí', N'Phim hài', N'Xin cảm ơn Trung Tâm Hướng Nghiệp Á Âu đã tài trợ địa điểm quay làm bánh cho ekip', N'FAPtv Cơm Nguội: Tập 204 - Người Cha Đãng Trí FPT Play: Xem phim và truyền hình trực tuyến không giới hạn ★ Website: https://go.onelink.me/1862450885/FPTP... ★ FPT PLAY Box: https://fptplay.tv #FAPTV, #Cơmnguội, #FPTPlay', 12000, 0, CAST(N'2023-08-04T01:28:47.693' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội: Tập 132 - Chuyện Nghề Diễn', N'tAyqv7qX1BA', N'https://img.youtube.com/vi/tAyqv7qX1BA/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn, Vinh Râu', N'Vinh Râu, Thái Vũ, Ribi Sachi, Thúy Kiều, Kim Suri,  Fap Team.', N'Phim hài', N'🎉🎉Đăng ký POPS Kids Learn để tham gia các khóa học online tương tác với giảng viên ngay nhé 👉 https://popskids.onelink.me/X36W/POPS...', N'Vì lý do bản quyền nên Tập FAPtv Cơm Nguội cũ sẽ gỡ xuống, chúng tôi xin upload lại tập này hôm nay. FAPtv Cơm Nguội: Tập 132 - Chuyện Nghề Diễn Muốn trị hói đầu và đẩy nhanh tiến trình tái tạo, ngăn ngừa việc rụng tóc? Chọn Maxxhair như Vinh Râu và Thái Vũ trong clip này ngay:  http://bit.ly/2zuYFYZ', 10000, 0, CAST(N'2023-08-04T02:58:06.603' AS DateTime));
INSERT INTO _video (title, href, poster, views, share, director, actor, category, heading, description, price, isActive, createdAt) VALUES (N'FAPtv Cơm Nguội 279: Xóm Nước Đen', N'hMRoaEuTnoM', N'https://img.youtube.com/vi/hMRoaEuTnoM/maxresdefault.jpg', 0, 0, N'Trần Đức Viễn', N'Vinh Râu, Thái Vũ, Ribi Sachi, Thúy Kiều, Kim Suri,  Fap Team.', N'Phim hài', N'FAPtv Cơm Nguội: Tập 176 - Quán Cafe Bất Ổn: Tình Đồng Chí', N'FAPtv Cơm Nguội 279: Xóm Nước Đen', 100000, 1, CAST(N'2023-08-05T02:44:19.413' AS DateTime));

INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'admin', N'admin123', N'84967363343', N'Lê Quang Nhựt', 1, 1, NULL)
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'nhut.thanthien17@gmail.com', N'123123', N'84905015900', N'Lê Quang Nhựt', 0, 1, NULL);
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'nhannt237@gmail.com', N'123123', N'0869996530 ', N'Nguyễn Thanh Nhàn', 0, 0, NULL);
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'phuongtri122@gmail.com', N'123123', N'0904050145 ', N'Trần Thanh Tâm', 0, 1, NULL);
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'phuongnguyen28@gmail.com', N'123123', N'0904050145 ', N'Nguyễn Huỳnh Phương', 0, 1, NULL);
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'thaipq21@gmail.com', N'123123', N'0904050134 ', N'Phan Quốc Thái', 0, 1, NULL);
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'khangndpc04859@fpt.edu.vn', N'123123', N'0905015940 ', N'Nguyễn Dỹ Khang', 0, 1, NULL);
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'ngochuyen@gmail.com', N'123123', N'0869929653 ', N'Nguyễn hồng hiếu', 0, 1, NULL);
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'tripheo@gmail.com', N'123123', N'0905015900 ', N'Nguyễn Thị Thuý Kiều', 0, 1, NULL);
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'ypx60202@omeie.com', N'123123', N'0905015902 ', N'Trần Trung Hiếu', 0, 1, NULL);
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'nhutlqpc04797@fpt.edu.vn', N't4uQ1H', N'0396040853 ', N'Lee Wang Nhut', 0, 0, NULL);
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'aow26378@nezid.com', N'123123', N'0905123456 ', N'Nguyễn Thị Thu Hương', 0, 1, N'uQuNAD42kY5j');
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'ioi53384@nezid.com', N'123123', N'0987654322 ', N'Đỗ Văn Thành', 0, 0, N'OOXkiShLlrg4');
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'nguyenyqn297@gmail.com', N'Pxn681', N'0727631560 ', N'Ngô Thủy', 0, 1, NULL);
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'kpt34658@nezid.com', N'123123', N'0869992530 ', N'Nguyễn Huỳnh Phương', 0, 1, N'GoD5kacXOcpK');
INSERT INTO _user ([email], [password], [phone], [fullName], [isAdmin], [isActive], [token]) VALUES (N'ewunehuok@email1.io', N'123123', N'0918451012 ', N'Trần Thanh Tân', 0, 1, N'x0v80zPP6b87');

INSERT INTO _comment (userId, videoId, content, createdAt) VALUES (1, 1, N'Phim con nhót mót chồng này quá anh em ơi', CAST(N'2023-07-18T21:33:28.263' AS DateTime));
INSERT INTO _comment (userId, videoId, content, createdAt) VALUES (1, 1, N'Phim này hay lắm nha nên em nha anh em', CAST(N'2023-07-18T22:02:05.467' AS DateTime));
INSERT INTO _comment (userId, videoId, content, createdAt) VALUES (1, 1, N'Trời ơi ước gì được xem phim này sớm hơn', CAST(N'2023-07-18T22:02:20.837' AS DateTime));
INSERT INTO _comment (userId, videoId, content, createdAt) VALUES (1, 1, N'Phim này đệ nhứt số một rồi ', CAST(N'2023-07-18T22:07:03.747' AS DateTime));
INSERT INTO _comment (userId, videoId, content, createdAt) VALUES (1, 2, N'Doraemon ơi', CAST(N'2023-07-18T22:53:24.503' AS DateTime));

INSERT INTO _order (vnp_TxnRef, videoId, userId, vnp_OrderInfo, vnp_ResponseCode, [vnp_TransactionNo], [vnp_Amount], [vnp_BankCode], [vnp_PayDate]) VALUES (N'59836674', 1, 1, N'Thanh toan don hang:59836674  ', N'00', N'14084747', 1000000, N'OCB                 ', CAST(N'2023-08-04T17:43:51.147' AS DateTime))
INSERT INTO _order (vnp_TxnRef, videoId, userId, vnp_OrderInfo, vnp_ResponseCode, [vnp_TransactionNo], [vnp_Amount], [vnp_BankCode], [vnp_PayDate]) VALUES (N'73526453', 4, 1, N'Thanh toan don hang:73526453  ', N'24', N'0       ', 1000000, N'VNPAY               ', CAST(N'2023-08-04T17:46:12.407' AS DateTime))
INSERT INTO _order (vnp_TxnRef, videoId, userId, vnp_OrderInfo, vnp_ResponseCode, [vnp_TransactionNo], [vnp_Amount], [vnp_BankCode], [vnp_PayDate]) VALUES (N'87334615', 2, 2, N'Thanh toan don hang:87334615  ', N'00', N'14084752', 1500000, N'JCB                 ', CAST(N'2023-08-04T17:50:52.900' AS DateTime))
INSERT INTO _order (vnp_TxnRef, videoId, userId, vnp_OrderInfo, vnp_ResponseCode, [vnp_TransactionNo], [vnp_Amount], [vnp_BankCode], [vnp_PayDate]) VALUES (N'43297020', 4, 5, N'Thanh toan don hang:43297020  ', N'00', N'14084772', 1000000, N'MASTERCARD          ', CAST(N'2023-08-04T18:05:04.557' AS DateTime))
INSERT INTO _order (vnp_TxnRef, videoId, userId, vnp_OrderInfo, vnp_ResponseCode, [vnp_TransactionNo], [vnp_Amount], [vnp_BankCode], [vnp_PayDate]) VALUES (N'94497026', 3, 5, N'Thanh toan don hang:94497026  ', N'00', N'14084942', 2500000, N'OCB                 ', CAST(N'2023-08-05T00:19:46.840' AS DateTime))
INSERT INTO _order (vnp_TxnRef, videoId, userId, vnp_OrderInfo, vnp_ResponseCode, [vnp_TransactionNo], [vnp_Amount], [vnp_BankCode], [vnp_PayDate]) VALUES (N'43220687', 1, 9, N'Thanh toan don hang:43220687  ', N'00', N'14084954', 1000000, N'OCB                 ', CAST(N'2023-08-05T00:56:29.530' AS DateTime))
INSERT INTO _order (vnp_TxnRef, videoId, userId, vnp_OrderInfo, vnp_ResponseCode, [vnp_TransactionNo], [vnp_Amount], [vnp_BankCode], [vnp_PayDate]) VALUES (N'44063870', 7, 3, N'Thanh toan don hang:44063870  ', N'00', N'14084971', 1500000, N'OCB                 ', CAST(N'2023-08-05T02:37:47.477' AS DateTime))
INSERT INTO _order (vnp_TxnRef, videoId, userId, vnp_OrderInfo, vnp_ResponseCode, [vnp_TransactionNo], [vnp_Amount], [vnp_BankCode], [vnp_PayDate]) VALUES (N'82595397', 4, 3, N'Thanh toan don hang:82595397  ', N'00', N'14084972', 1000000, N'OCB                 ', CAST(N'2023-08-05T02:39:10.143' AS DateTime))
INSERT INTO _order (vnp_TxnRef, videoId, userId, vnp_OrderInfo, vnp_ResponseCode, [vnp_TransactionNo], [vnp_Amount], [vnp_BankCode], [vnp_PayDate]) VALUES (N'94734173', 1, 3, N'Thanh toan don hang:94734173  ', N'00', N'14084973', 2000000, N'OCB                 ', CAST(N'2023-08-05T02:41:55.133' AS DateTime))
INSERT INTO _order (vnp_TxnRef, videoId, userId, vnp_OrderInfo, vnp_ResponseCode, [vnp_TransactionNo], [vnp_Amount], [vnp_BankCode], [vnp_PayDate]) VALUES (N'28997598', 4, 7, N'Thanh toan don hang:28997598  ', N'24', N'0       ', 1000000, N'VNPAY               ', CAST(N'2023-08-05T02:42:42.237' AS DateTime))
INSERT INTO _order (vnp_TxnRef, videoId, userId, vnp_OrderInfo, vnp_ResponseCode, [vnp_TransactionNo], [vnp_Amount], [vnp_BankCode], [vnp_PayDate]) VALUES (N'54025200', 2, 8, N'Thanh toan don hang:54025200  ', N'00', N'14085139', 10000000, N'OCB                 ', CAST(N'2023-08-05T14:07:42.013' AS DateTime))

INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (1, 1, CAST(N'2023-08-01T14:08:44.517' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (1, 2, CAST(N'2023-08-01T14:11:38.550' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (7, 1, CAST(N'2023-08-01T23:03:57.997' AS DateTime), 1, CAST(N'2023-08-03T15:40:42.807' AS DateTime))
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (7, 2, CAST(N'2023-08-02T00:34:26.033' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (7, 9, CAST(N'2023-08-02T00:34:38.900' AS DateTime), 1, CAST(N'2023-08-03T15:38:37.153' AS DateTime))
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (7, 6, CAST(N'2023-08-02T00:36:22.887' AS DateTime), 1, CAST(N'2023-08-02T01:09:34.523' AS DateTime))
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (8, 12, CAST(N'2023-08-03T15:43:06.827' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (1, 12, CAST(N'2023-08-04T00:34:42.393' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (1, 9, CAST(N'2023-08-04T02:33:28.073' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (1, 11, CAST(N'2023-08-04T02:43:49.707' AS DateTime), 1, CAST(N'2023-08-04T16:49:04.430' AS DateTime))
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (1, 5, CAST(N'2023-08-04T02:51:42.367' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (2, 5, CAST(N'2023-08-04T02:51:48.137' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (3, 5, CAST(N'2023-08-04T02:51:49.790' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (4, 5, CAST(N'2023-08-04T02:51:51.260' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (5, 2, CAST(N'2023-08-04T16:50:58.713' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (4, 15, CAST(N'2023-08-04T17:58:10.817' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (5, 22, CAST(N'2023-08-04T18:03:21.763' AS DateTime), 1, CAST(N'2023-08-04T18:03:41.670' AS DateTime))
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (5, 4, CAST(N'2023-08-04T18:03:49.170' AS DateTime), 1, CAST(N'2023-08-04T18:05:35.503' AS DateTime))
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (3, 4, CAST(N'2023-08-04T19:47:04.287' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (3, 16, CAST(N'2023-08-05T00:13:38.873' AS DateTime), 1, CAST(N'2023-08-05T02:35:20.980' AS DateTime))
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (3, 41, CAST(N'2023-08-05T02:25:00.717' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (14, 21, CAST(N'2023-08-05T02:33:37.257' AS DateTime), 1, CAST(N'2023-08-05T02:33:40.610' AS DateTime))
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (14, 22, CAST(N'2023-08-05T02:33:51.860' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (14, 23, CAST(N'2023-08-05T02:33:55.147' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (3, 11, CAST(N'2023-08-05T02:36:27.753' AS DateTime), 1, CAST(N'2023-08-05T02:36:43.457' AS DateTime))
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (3, 15, CAST(N'2023-08-05T02:39:26.797' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (3, 18, CAST(N'2023-08-05T02:41:07.667' AS DateTime), 0, NULL)
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (6, 10, CAST(N'2023-08-05T02:45:39.537' AS DateTime), 1, CAST(N'2023-08-05T02:45:57.957' AS DateTime))
INSERT INTO _history ([userId], [videoId], viewedAt, [isLiked], likedAt) VALUES (13, 10, CAST(N'2023-08-05T14:07:26.680' AS DateTime), 0, NULL)

INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 2, 4, CAST(N'2023-07-21T00:47:09.257' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 3, 4, CAST(N'2023-07-20T00:48:19.377' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 4, 4, CAST(N'2023-07-17T17:09:11.030' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 5, 4, CAST(N'2023-08-03T23:59:48.037' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 6, 4, CAST(N'2023-08-04T10:37:55.250' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 7, 5, CAST(N'2023-07-18T15:17:43.350' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (4, 4, 3, CAST(N'2023-07-17T19:06:36.023' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 16, 5, CAST(N'2023-08-02T02:23:26.850' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 15, 4, CAST(N'2023-07-23T02:08:46.990' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 20, 4, CAST(N'2023-07-17T21:23:37.127' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 18, 3, CAST(N'2023-07-28T01:08:38.987' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 14, 5, CAST(N'2023-08-02T01:55:59.707' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 11, 5, CAST(N'2023-07-18T16:40:22.717' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (2, 22, 4, CAST(N'2023-07-19T22:26:43.320' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (7, 1, 3, CAST(N'2023-07-19T23:03:14.690' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 20, 5, CAST(N'2023-07-20T01:22:37.163' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (3, 21, 3, CAST(N'2023-07-21T01:40:10.277' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (3, 18, 4, CAST(N'2023-07-21T01:40:36.370' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (3, 1, 5, CAST(N'2023-08-04T18:24:33.467' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (3, 15, 2, CAST(N'2023-07-21T01:41:21.180' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (3, 19, 2, CAST(N'2023-07-21T01:41:55.327' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (3, 4, 2, CAST(N'2023-07-21T01:42:06.540' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (4, 1, 3, CAST(N'2023-07-24T00:23:23.747' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (5, 4, 5, CAST(N'2023-07-24T19:05:10.683' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (4, 2, 3, CAST(N'2023-07-26T22:32:03.600' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (5, 2, 4, CAST(N'2023-07-26T23:18:12.677' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (6, 11, 3, CAST(N'2023-07-27T15:37:42.570' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (6, 12, 5, CAST(N'2023-07-27T15:42:05.590' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (6, 14, 2, CAST(N'2023-07-28T13:23:18.500' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (6, 16, 3, CAST(N'2023-08-02T01:07:11.223' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (7, 1, 5, CAST(N'2023-08-03T15:40:06.677' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (9, 1, 3, CAST(N'2023-08-04T00:01:06.290' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (7, 4, 4, CAST(N'2023-08-03T15:38:11.397' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 13, 4, CAST(N'2023-08-04T02:33:30.723' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (1, 12, 3, CAST(N'2023-08-04T16:49:03.530' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (8, 16, 3, CAST(N'2023-08-04T17:47:24.307' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (4, 6, 3, CAST(N'2023-08-04T17:58:12.380' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (9, 8, 5, CAST(N'2023-08-04T18:03:43.057' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (9, 4, 4, CAST(N'2023-08-04T18:05:34.503' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (9, 2, 5, CAST(N'2023-08-04T18:07:44.010' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (9, 3, 3, CAST(N'2023-08-04T19:47:05.967' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (9, 9, 4, CAST(N'2023-08-05T02:32:12.747' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (15, 75, 5, CAST(N'2023-08-05T02:33:39.917' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (12, 16, 4, CAST(N'2023-08-05T02:34:17.637' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (3, 16, 4, CAST(N'2023-08-05T02:35:21.573' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (3, 20, 5, CAST(N'2023-08-05T02:36:42.633' AS DateTime))
INSERT INTO _rating ([userId], [videoId], star, createdAt) VALUES (13, 21, 5, CAST(N'2023-08-05T02:45:56.017' AS DateTime))