INSERT INTO Video (ACTORS, CATEGORY, CREATED_AT, DESCRIPTION, DIRECTOR, HEADING, HREF, ISACTIVE, POSTER, PRICE, SHARES, TITLE, VIEWS)
VALUES ('dien vien' ,'dao dien' ,NULL ,'' ,'' ,'' ,'' ,1 ,NULL ,'' ,2 ,'' ,4)


